name: Pull Request
'on':
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  tests: 
    runs-on: ubuntu-latest  
    steps: 
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: npm install
        run: |
          npm install
      - name: Generate build
        run: | 
          npm run build
      - name: Build tests
        run: | 
          npm run build:test
      - name: Run tests
        run: | 
          npm run test

  sample:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: npm install
        run: |
          npm install
      - name: Generate build
        run: | 
          npm run build
      - name: Generate dependency diff
        id: diff
        uses: ./
        with:
          before: sample/before.txt
          after: sample/after.txt
          output_to_file: true
          output_to_file_name: diff.txt
          post_pr_comment: true
      - name: Archive dependency diff
        uses: actions/upload-artifact@v7
        with:
          name: dependency-diff
          path: diff.txt